[workspace]
members = [
    "malwerks_vk",
    "malwerks_resources",
    "malwerks_render",
    "malwerks_tools",
    "malwerks_playground",

    "malwerks_dds",
    "malwerks_ply",
    "malwerks_gltf",
    "malwerks_external"
]
