[package]
name = "malwerks_core"
version = "0.1.0"
authors = ["Kyrylo Bazhenov <bazhenovc@gmail.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
malwerks_vk = { path = "../malwerks_vk" }
malwerks_bundles = { path = "../malwerks_bundles" }

log = "*"
puffin = "*"
