[package]
name = "malwerks_ply"
version = "0.1.0"
authors = ["Kyrylo Bazhenov <bazhenovc@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = "*"
seek_bufread = "*" # TODO: remove this once "bufreader_seek_relative" is available
log = "*"
rle_vec = "*"
